#!/usr/bin/env node
/*
 *********************************************************************************
 *                     Copyright (C) 2019 wystan
 *
 *       filename: ua_test.js
 *    description:
 *        created: 2019-03-23 13:52:50
 *         author: wystan
 *
 *********************************************************************************
 */

const ua = require("./ua");
const parser = ua.UserAgentParser;
const desc = ua.UserAgentDescriptor;

const log = console.log;
const ua_tab = [
    // ie 6/7/8/9/10/11
    {
        ua: "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; SV1)",
        result: new desc("ie", "6.0", "windows", "2000")
    },{
        ua: "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; WOW64; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)",
        result: new desc("ie", "7.0", "windows", "xp")
    },{
        ua: "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)",
        result: new desc("ie", "8.0", "windows", "2003")
    },{
        ua: "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)",
        result: new desc("ie", "9.0", "windows", "7")
    },{
        ua: "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)",
        result: new desc("ie", "10.0", "windows", "8")
    },{
        ua: "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Shuame; rv:11.0) like Gecko",
        result: new desc("ie", "11.0", "windows", "8.1")
    },{
        ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393",
        result: new desc("edge", "14.14393", "windows", "10")
    },

    // edge
    {
        ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063",
        result: new desc("edge", "15.15063", "windows", "10")
    },

    // chrome
    {
        ua: "Mozilla/5.0 (Linux; Android 7.1; Mi A1 Build/N2G47H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0 Mobile Safari/537.36",
        result: new desc("chrome", "58.0", "android", "7.1")
    },{
        ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/64.0 Mobile/15D60 Safari/604.1",
        result: new desc("chrome", "64.0", "ios", "11.2.5")
    },{
        ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0 Safari/537.36",
        result: new desc("chrome", "65.0", "macos", "10.13.4")
    },{
        ua: "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497 Safari/537.36",
        result: new desc("chrome", "69.0.3497", "windows", "7")
    },{
        ua: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36",
        result: new desc("chrome", "69.0.3497.92", "linux", "")
    },{
        ua: "Mozilla/5.0 (Linux; Android 9; TNY-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626 Mobile Safari/537.36",
        result: new desc("chrome", "72.0.3626", "android", "9")
    },

    // safari
    {
        ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15",
        result: new desc("safari", "11.1.2", "macos", "10.13.6")
    },{
        ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1",
        result: new desc("safari", "11.0", "ios", "11.3")
    },{
        ua: "Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1",
        result: new desc("safari", "10.0", "ios", "10.3.3")
    },{
        ua: "Mozilla/5.0 (iPod touch; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1",
        result: new desc("safari", "9.0", "ios", "9.3.5")
    },

    // firefox
    {
        ua: "Mozilla/5.0 (Android 6.0.1; Mobile; rv:48.0) Gecko/48.0 Firefox/48.0",
        result: new desc("firefox", "48.0", "android", "6.0.1")
    },{
        ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) FxiOS/7.5b3349 Mobile/14F89 Safari/603.2.4",
        result: new desc("firefox", "7.5b3349", "ios", "10.3.2")
    },{
        ua: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0",
        result: new desc("firefox", "63.0", "windows", "7")
    },{
        ua: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0",
        result: new desc("firefox", "61.0", "linux", "")
    },{
        ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0",
        result: new desc("firefox", "52.0", "macos", "10.12")
    },
];

function main() {
    log("==> starting")
    for (let i of ua_tab) {
        let rst = parser.parse(i.ua);
        if (rst && rst.equal(i.result)) {
            log(rst);
            continue;
        }
        log("ERROR:", rst, "!=", i.result);
        break;
    }
    log("==>done.")
}

/************************************* END **************************************/
main();
